# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateTimeField(verbose_name='DATE')),
                ('EXCH', models.CharField(max_length=10)),
                ('EXCH_FULL', models.CharField(max_length=100)),
                ('ENABLED', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
    ]
