# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanges',
            old_name='created',
            new_name='ccreated',
        ),
        migrations.RenameField(
            model_name='exchanges',
            old_name='enabled',
            new_name='eenabled',
        ),
        migrations.RenameField(
            model_name='exchanges',
            old_name='exch',
            new_name='eexch',
        ),
        migrations.RenameField(
            model_name='exchanges',
            old_name='exch_full',
            new_name='eexch_full',
        ),
        migrations.RenameField(
            model_name='exchanges',
            old_name='modified',
            new_name='mmodified',
        ),
    ]
