# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('ticker', models.CharField(max_length=6)),
                ('volume', models.IntegerField()),
                ('value', models.FloatField()),
                ('trades', models.IntegerField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('change', models.FloatField()),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trades',
            },
        ),
    ]
