# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateTimeField(verbose_name='DATE')),
                ('TICKER', models.CharField(max_length=6)),
                ('VOLUME', models.IntegerField()),
                ('VALUE', models.FloatField()),
                ('TRADES', models.IntegerField()),
                ('HIGH', models.FloatField()),
                ('LOW', models.FloatField()),
                ('OPEN', models.FloatField()),
                ('CLOSE', models.FloatField()),
                ('CHANGE', models.FloatField()),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trades',
            },
        ),
    ]
