# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='MODIFIED',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFIED'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='DATE',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DATE'),
        ),
    ]
