# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mse', '0002_auto_20170217_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='CREATED',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='CREATED'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trades',
            name='DATE',
            field=models.DateTimeField(verbose_name='DATE'),
        ),
    ]
