# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('security_id', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('expenses', models.FloatField()),
            ],
        ),
    ]
