# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('portfolio_id', models.IntegerField()),
                ('security_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('expenses', models.FloatField()),
            ],
            options={
                'verbose_name': 'Portfolio Data',
                'verbose_name_plural': 'Portfolio Data',
            },
        ),
    ]
