# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_data',
            name='expenses',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
