# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('modified', models.DateTimeField(verbose_name='modified')),
                ('uri', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
    ]
