# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uri', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
