# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginbar', '0002_auto_20170217_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='uri',
            field=models.CharField(max_length=1000),
        ),
    ]
