# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginbar', '0003_auto_20170220_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
